apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xtenants.wadtfy.bmwgroup.net
spec:
  group: wadtfy.bmwgroup.net
  names:
    kind: XTenant
    plural: xtenants
  versions:
    - name: v1beta1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                stage:
                  type: string
                  description: "The stage where this tenant config should be deployed into."
                  enum: ["lab", "int", "prod"]
                oidcProviderId:
                  type: string
                  description: "Id of the OIDC provider that is used with EKS."
                product:
                  type: string
                  description: "Tenant's product name."
                region:
                  type: string
                  description: "Tenant's AWS Account region."
                tenantAccountId:
                  type: string
                  description: "The AWS account id for which to create namespaces on the Kubernetes cluster."
                namespace:
                  type: string
                  description: "The namespace to be created."
              required:
                - stage
                - oidcProviderId
                - product
                - region
                - namespace
                - tenantAccountId
            status:
              type: object
              properties:
                providerConfig:
                  description: "Name of the Provider Config to be used by this component."
                  type: string
