apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xnamespaces.wadtfy.bmwgroup.net
spec:
  group: wadtfy.bmwgroup.net
  names:
    kind: XNamespace
    plural: xnamespaces
  claimNames:
    kind: Namespace
    plural: namespaces
  versions:
    - name: v1beta1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespaceName:
                  type: string
                  description: "Name of the Namespace"
                enforcePolicyLevel:
                  type: string
                  description: "Enforce Policy Level"
                  enum: ["privileged", "baseline", "restricted"]
                enforcePolicyVersion:
                  type: string
                  description: "Enforce Policy Version (default: latest)"
                warnPolicyLevel:
                  type: string
                  description: "Policy Level"
                  enum: ["privileged", "baseline", "restricted"]
                warnPolicyVersion:
                  type: string
                  description: "Warn Policy Version (default: latest)"
                auditPolicyLevel:
                  type: string
                  description: "Policy Level"
                  enum: ["privileged", "baseline", "restricted"]
                auditPolicyVersion:
                  type: string
                  description: "Audit Policy Version (default: latest)"
              required:
                - namespaceName
                - enforcePolicyLevel
