apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: tenant-default
  labels:
    crossplane.io/xrd: xtenantconfigs.wadtfy.bmwgroup.net
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  environment:
    environmentConfigs:
      - type: Reference
        ref:
          name: wadtfy-env
  compositeTypeRef:
    apiVersion: wadtfy.bmwgroup.net/v1beta1
    kind: XTenant
  patchSets:
    - name: "k8s-tags"
      patches:
        - type: FromEnvironmentFieldPath
          fromFieldPath: "eksAccountID"
          toFieldPath: "spec.forProvider.manifest.metadata.annotations[wadtfy.bmwgroup.net/cluster-account-id]"
        - fromFieldPath: "spec.product"
          toFieldPath: "spec.forProvider.manifest.metadata.annotations[wadtfy.bmwgroup.net/product-name]"
        - fromFieldPath: "metadata.name"
          toFieldPath: "spec.forProvider.manifest.metadata.annotations[wadtfy.bmwgroup.net/component-name]"
  resources:
    - name: TenantEnv
      base:
        apiVersion: wadtfy.bmwgroup.net/v1beta1
        kind: XTenantEnv
      patches:
        - type: FromEnvironmentFieldPath
          fromFieldPath: "stage"
          toFieldPath: "spec.env.stage"
        - type: ToCompositeFieldPath
          fromFieldPath: "spec.env.stage"
          toFieldPath: "status.env.stage"
    - name: TenantProviderConfig
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          deletionPolicy: Delete
          forProvider:
            manifest:
              apiVersion: aws.crossplane.io/v1beta1
              kind: ProviderConfig
              metadata:
                annotations:
                  wadtfy.bmwgroup.net/xrd-type: XTenant
                  wadtfy.bmwgroup.net/xrd-version: v1beta1
                  wadtfy.bmwgroup.net/cluster-account-id:
                  wadtfy.bmwgroup.net/product-name:
                  wadtfy.bmwgroup.net/component-name:
                name:
              spec:
                assumeRoleWithWebIdentity:
                  roleARN:
                  roleSessionName:
                credentials:
                  source: InjectedIdentity
          providerConfigRef:
            name:
      patches:
        - type: PatchSet
          patchSetName: "k8s-tags"
        - type: ToCompositeFieldPath
          fromFieldPath: "spec.forProvider.manifest.metadata.name"
          toFieldPath: "status.providerConfig"
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: "spec.product"
              - fromFieldPath: "spec.awsAccountId"
              - fromFieldPath: "spec.namespace"
            strategy: string
            string:
              fmt: "%s-%s-%s"
          toFieldPath: "spec.forProvider.manifest.metadata.name"
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: "spec.awsAccountId"
              - fromFieldPath: "status.env.stage"
              - fromFieldPath: "spec.product"
            strategy: string
            string:
              fmt: "arn:aws:iam::%s:role/wadtfy/wadtfy-%s-%s-iac-sa-role"
          toFieldPath: "spec.forProvider.manifest.spec.assumeRoleWithWebIdentity.roleARN"
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: "eksAccountID"
              - fromFieldPath: "status.env.stage"
              - fromFieldPath: "spec.product"
            strategy: string
            string:
              fmt: "provider-config-%s-%s-%s-session"
          toFieldPath: "spec.forProvider.manifest.spec.assumeRoleWithWebIdentity.roleSessionName"
        - type: FromEnvironmentFieldPath
          fromFieldPath: "providerConfigKubernetes"
          toFieldPath: "spec.providerConfigRef.name"
    - name: TenantEnvironmentConfig
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha1
        kind: Object
        spec:
          deletionPolicy: Delete
          forProvider:
            manifest:
              apiVersion: apiextensions.crossplane.io/v1alpha1
              kind: EnvironmentConfig
              metadata:
                annotations:
                  wadtfy.bmwgroup.net/xrd-type: XTenant
                  wadtfy.bmwgroup.net/xrd-version: v1beta1
                  wadtfy.bmwgroup.net/cluster-account-id:
                  wadtfy.bmwgroup.net/product-name:
                  wadtfy.bmwgroup.net/component-name:
                labels:
                  category: "wadtfy-tenant"
                  namespace:
                name:
              data:
                product:
                awsAccountId:
                region:
                providerConfig:
          providerConfigRef:
            name:
      patches:
        - type: PatchSet
          patchSetName: "k8s-tags"
        - fromFieldPath: "spec.namespace"
          toFieldPath: "spec.forProvider.manifest.metadata.labels[namespace]"
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: "spec.product"
              - fromFieldPath: "spec.awsAccountId"
              - fromFieldPath: "spec.namespace"
            strategy: string
            string:
              fmt: "system-env-%s-%s-%s"
          toFieldPath: "spec.forProvider.manifest.metadata.name"
        - fromFieldPath: "spec.awsAccountId"
          toFieldPath: "spec.forProvider.manifest.data.awsAccountId"
        - fromFieldPath: "spec.product"
          toFieldPath: "spec.forProvider.manifest.data.product"
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.manifest.data.region"
        - fromFieldPath: "status.providerConfig"
          toFieldPath: "spec.forProvider.manifest.data.providerConfig"
        - type: FromEnvironmentFieldPath
          fromFieldPath: "providerConfigKubernetes"
          toFieldPath: "spec.providerConfigRef.name"
    - name: SecretStore
      base:
        apiVersion: wadtfy.bmwgroup.net/v1beta1
        kind: XSecretStore
      patches:
        - type: FromEnvironmentFieldPath
          fromFieldPath: "irsaTenantCompositionRef"
          toFieldPath: "spec.irsaCompositionRef"
        - type: FromEnvironmentFieldPath
          fromFieldPath: "providerConfigKubernetes"
          toFieldPath: "spec.providerConfigKubernetes"
        - fromFieldPath: "spec.product"
          toFieldPath: "spec.product"
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.region"
        - fromFieldPath: "spec.awsAccountId"
          toFieldPath: "spec.awsAccountId"
        - fromFieldPath: "spec.namespace"
          toFieldPath: "spec.namespace"
