apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xsecretstores.wadtfy.bmwgroup.net
spec:
  group: wadtfy.bmwgroup.net
  names:
    kind: XSecretStore
    plural: xsecretstores
  versions:
    - name: v1beta1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                product:
                  type: string
                  description: "Tenant's product name."
                awsAccountId:
                  type: string
                  description: "The AWS account id for which to create namespaces on the Kubernetes cluster."
                namespace:
                  type: string
                  description: "Tenant's specific namespace where to create dependent resources for external secrets."
              required:
                - product
                - awsAccountId
                - namespace
