apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xsecretstores.wadtfy.bmwgroup.net
spec:
  group: wadtfy.bmwgroup.net
  names:
    kind: XSecretStore
    plural: xsecretstores
  versions:
    - name: v1beta1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                irsaCompositionRef:
                  type: string
                  description: "The name of the IRSA Composition Ref that should be used for IRSA creation. This value is stored in the global wadtfy-env EnvironmentConfig."
                providerConfigKubernetes:
                  type: string
                  description: "The name of the K8S ProviderConfig. This value is stored in the global wadtfy-env EnvironmentConfig."
                product:
                  type: string
                  description: "Tenant's product name."
                region:
                  type: string
                  description: "Tenant's AWS Account region."
                awsAccountId:
                  type: string
                  description: "The AWS account id for which to create namespaces on the Kubernetes cluster."
                namespace:
                  type: string
                  description: "Tenant's specific namespace where to create dependent resources for external secrets."
              required:
                - irsaCompositionRef
                - providerConfigKubernetes
                - product
                - region
                - awsAccountId
                - namespace
