apiVersion: kms.aws.crossplane.io/v1alpha1
kind: Key
metadata:
  name: {{ .Values.components.global.name }}
spec:
  deletionPolicy: {{ .Values.components.global.deletionPolicy }}
  forProvider:
    tags:
      - tagKey: "wadtfy.bmwgroup.net/xrd-type"
        tagValue: "XTenantFilesystemAbstraction"
      - tagKey: "wadtfy.bmwgroup.net/xrd-version"
        tagValue: "v1beta1"
      {{- range $tagKey, $tagValue := .Values.tags }}
      - tagKey: {{ $tagKey }}
        tagValue: {{ $tagValue }}
      {{- end }}
    enableKeyRotation: true
    enabled: true
    policy: |
      {
        "Version": "2012-10-17",
        "Id": "key-policy",
        "Statement": [
          {
            "Sid": "Enable IAM User Permissions",
            "Effect": "Allow",
            "Principal": {
              "AWS": "arn:aws:iam::{{ .Values.config.tenant.awsAccountId }}:root"
            },
            "Action": "kms:*",
            "Resource": "*"
          }
        ]
      }
    region: {{ .Values.components.global.region }}
  providerConfigRef:
    name: {{ .Values.providerConfig.aws }}
