apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xtenantfilesystemabstractions.wadtfy.bmwgroup.net
spec:
  group: wadtfy.bmwgroup.net
  names:
    kind: XTenantFilesystemAbstraction
    plural: xtenantfilesystemabstractions
  claimNames:
    kind: TenantFilesystemAbstraction
    plural: tenantfilesystemabstractions
  versions:
    - name: v1beta1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                status:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
