name: Release Charts

on:
  push:
    branches:
      - master
    paths:
      - 'charts/v1/**'
      - 'charts/v1alpha1/**'
      - 'charts/v1beta1/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Run chart-releaser-v1
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: charts/v1/
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          CR_RELEASE_NOTES_FILE: CHANGELOG.md

      - name: Run chart-releaser-v1alpha1
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: charts/v1alpha1/
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          CR_RELEASE_NOTES_FILE: CHANGELOG.md

      - name: Run chart-releaser-v1beta1
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: charts/v1beta1/
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          CR_RELEASE_NOTES_FILE: CHANGELOG.md

